name: pciutils
version: 3.3.1-3
summary: Linux PCI Utilities
description: This package contains various utilities for inspecting and setting of
    devices connected to the PCI bus.
confinement: strict
grade: stable

apps:
    lspci:
        command: usr/bin/lspci
        plugs: [hardware-observe]
        aliases:
            - lspci

parts:
    pciutils:
        plugin: nil 
        stage-packages:
            - pciutils 
        prime:
            - -usr/share/doc
            - -usr/share/man
